### ISSUE TITLE
Sugestão para README

### ISSUE THREAD

**Issue by ErickFSilva** [ErickFSilvaProg/DIO-Formacao-Github-Certification#1]
Como **o propósito desse repositório é armazenar o conteúdo desenvolvido na formação** e tendo o arquivo **README** como referências para essas aulas, seria interessante colocar, ao final de cada capítulo, um ***check*** para marcar a conclusão do mesmo.

Exemplo:

> ### Introdução aos conceitos de Git e Github
> * Principios de Git e Github [x] ***<- Dessa forma***
> * Autenticação [X] ***<- Ou dessa forma***
> * Colaboração no Github [ ]
> * Formatação com markdown [ ]
> * Explorando colaboração e markdown [ ]
> * Desafios de código - Formação Github Certification [ ]

**Comment by ErickFSilvaProg** [comment]
Gostei da idéia, vou proceder.
